version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: chatzone_postgres
    environment:
      POSTGRES_DB: chatzone_db
      POSTGRES_USER: chatzone_user
      POSTGRES_PASSWORD: chatzone_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chatzone_network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: chatzone_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - chatzone_network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatzone_backend
    environment:
      NODE_ENV: development
      PORT: 5000
      DATABASE_URL: postgresql://chatzone_user:chatzone_password@postgres:5432/chatzone_db
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your_super_secret_jwt_key_for_development
      CLIENT_URL: http://localhost:19006
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - chatzone_network
    restart: unless-stopped
    command: npm run dev

  # pgAdmin (Database Management UI)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: chatzone_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@chatzone.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - chatzone_network
    restart: unless-stopped

  # Redis Commander (Redis Management UI)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: chatzone_redis_commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - chatzone_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  chatzone_network:
    driver: bridge